name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newshub_test
    services:
      db:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: 127.0.0.1
          RAILS_ENV: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Add yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Prepare Database
        run: |
          bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
          # RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDB: newshub
        continue-on-error: true
        run: |
          bundle exec rspec ./spec
