# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push or pull request events
on: [ push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3
      
      # - name: Prepare Database
      #   run: |
      #     bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          # RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
          PG_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bin/rails db:test:prepare
          bundle exec rake
