name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: test
      POSTGRES_HOST: localhost
    services:
      db:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Add yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: Install Gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: Prepare Database
        run: |
          bundle exec rails db:setup

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/test
          RAILS_ENV: test
          # RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          PG_DATABASE: db
        continue-on-error: true
        run: |
          bundle exec rspec
